version: '3'
services:

  # front-end service
  www:
    build: ./www
    volumes:
      - ./www:/usr/src/app     
    restart: unless-stopped  

  # back-end service
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db    
    restart: unless-stopped
  
  # MongoDb
  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: unless-stopped
  
  # NGINX proxy
  proxy:
    build: ./proxy
    ports: 
      - "8080:80"
    depends_on: 
      - www
      - server  
    restart: unless-stopped
    