version: '3'
services:
  server:
    command: nodemon -L --exec npm start
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db
    restart: unless-stopped
  
  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: unless-stopped
  
  www:
    build: ./www
    volumes:
      - ./www:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  
  proxy:
    build: ./proxy
    ports: 
      - "80:80"
    depends_on: 
      - www
      - server  
    restart: unless-stopped
    